# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from api.info_api import InfoApi  # noqa: E501
from fronius_api.rest import ApiException


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self):
        self.api = api.info_api.InfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_info_release(self):
        """Test case for get_info_release

        This method returns currently deployed version of service, and it's date.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
