# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from models.system_message_list import SystemMessageList  # noqa: E501
from fronius_api.rest import ApiException


class TestSystemMessageList(unittest.TestCase):
    """SystemMessageList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemMessageList(self):
        """Test SystemMessageList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.system_message_list.SystemMessageList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
