# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from models.counter import Counter  # noqa: E501
from fronius_api.rest import ApiException


class TestCounter(unittest.TestCase):
    """Counter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCounter(self):
        """Test Counter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.counter.Counter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
