# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from models.release_info import ReleaseInfo  # noqa: E501
from fronius_api.rest import ApiException


class TestReleaseInfo(unittest.TestCase):
    """ReleaseInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseInfo(self):
        """Test ReleaseInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.release_info.ReleaseInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
