# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from api.aggregated_api import AggregatedApi  # noqa: E501
from fronius_api.rest import ApiException


class TestAggregatedApi(unittest.TestCase):
    """AggregatedApi unit test stubs"""

    def setUp(self):
        self.api = api.aggregated_api.AggregatedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aggregated_data_days(self):
        """Test case for get_aggregated_data_days

        This method returns daily aggregated data for a specific PV system for a specific month of a year.  # noqa: E501
        """
        pass

    def test_get_aggregated_data_months(self):
        """Test case for get_aggregated_data_months

        This method returns monthly aggregated data for a specific PV system for a specific year.  # noqa: E501
        """
        pass

    def test_get_aggregated_data_specific_day(self):
        """Test case for get_aggregated_data_specific_day

        This method returns daily aggregated data for a specific PV system for a specific date.  # noqa: E501
        """
        pass

    def test_get_aggregated_data_specific_month(self):
        """Test case for get_aggregated_data_specific_month

        This method returns monthly aggregated data for a specific PV system for a specific month of a year.  # noqa: E501
        """
        pass

    def test_get_aggregated_data_specific_year(self):
        """Test case for get_aggregated_data_specific_year

        This method returns annual aggregated data for a specific PV system for a specific year.  # noqa: E501
        """
        pass

    def test_get_aggregated_data_total(self):
        """Test case for get_aggregated_data_total

        This method returns total lifetime aggregated data for a specific PV system.  # noqa: E501
        """
        pass

    def test_get_aggregated_data_years(self):
        """Test case for get_aggregated_data_years

        This method returns annual aggregated data for a specific PV system for all years since installation.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
