# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from api.energy_flow_api import EnergyFlowApi  # noqa: E501
from fronius_api.rest import ApiException


class TestEnergyFlowApi(unittest.TestCase):
    """EnergyFlowApi unit test stubs"""

    def setUp(self):
        self.api = api.energy_flow_api.EnergyFlowApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_flow_data(self):
        """Test case for get_flow_data

        This method returns energy flow values for a specific PV system  # noqa: E501
        """
        pass

    def test_get_flow_data_for_specific_device(self):
        """Test case for get_flow_data_for_specific_device

        """
        pass


if __name__ == '__main__':
    unittest.main()
