# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from models.energy_flow_status import EnergyFlowStatus  # noqa: E501
from fronius_api.rest import ApiException


class TestEnergyFlowStatus(unittest.TestCase):
    """EnergyFlowStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnergyFlowStatus(self):
        """Test EnergyFlowStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.energy_flow_status.EnergyFlowStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
