# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from api.system_messages_api import SystemMessagesApi  # noqa: E501
from fronius_api.rest import ApiException


class TestSystemMessagesApi(unittest.TestCase):
    """SystemMessagesApi unit test stubs"""

    def setUp(self):
        self.api = api.system_messages_api.SystemMessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_device_messages(self):
        """Test case for get_device_messages

        """
        pass

    def test_get_device_messages_count(self):
        """Test case for get_device_messages_count

        """
        pass

    def test_get_system_messages(self):
        """Test case for get_system_messages

        """
        pass

    def test_get_system_messages_count(self):
        """Test case for get_system_messages_count

        """
        pass


if __name__ == '__main__':
    unittest.main()
