# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fronius_api
from models.pv_system import PvSystem  # noqa: E501
from fronius_api.rest import ApiException


class TestPvSystem(unittest.TestCase):
    """PvSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPvSystem(self):
        """Test PvSystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pv_system.PvSystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
