# coding: utf-8

# flake8: noqa
"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from fronius_api.models.address import Address
from fronius_api.models.agg_channel import AggChannel
from fronius_api.models.agg_data import AggData
from fronius_api.models.agg_log_period import AggLogPeriod
from fronius_api.models.aggregated_values import AggregatedValues
from fronius_api.models.counter import Counter
from fronius_api.models.device import Device
from fronius_api.models.device_ids_only import DeviceIdsOnly
from fronius_api.models.device_list import DeviceList
from fronius_api.models.energy_flow import EnergyFlow
from fronius_api.models.energy_flow_channel import EnergyFlowChannel
from fronius_api.models.energy_flow_data import EnergyFlowData
from fronius_api.models.energy_flow_status import EnergyFlowStatus
from fronius_api.models.error_response import ErrorResponse
from fronius_api.models.historical_channel import HistoricalChannel
from fronius_api.models.historical_data import HistoricalData
from fronius_api.models.historical_values import HistoricalValues
from fronius_api.models.input_new_token import InputNewToken
from fronius_api.models.paging_links import PagingLinks
from fronius_api.models.problem_details import ProblemDetails
from fronius_api.models.pv_system import PvSystem
from fronius_api.models.pv_system_ids_only import PvSystemIdsOnly
from fronius_api.models.pv_system_list import PvSystemList
from fronius_api.models.release_info import ReleaseInfo
from fronius_api.models.sensor import Sensor
from fronius_api.models.system_message import SystemMessage
from fronius_api.models.system_message_list import SystemMessageList
from fronius_api.models.token import Token
