# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EnergyFlowData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'log_date_time': 'str',
        'channels': 'list[EnergyFlowChannel]'
    }

    attribute_map = {
        'log_date_time': 'logDateTime',
        'channels': 'channels'
    }

    def __init__(self, log_date_time=None, channels=None):  # noqa: E501
        """EnergyFlowData - a model defined in Swagger"""  # noqa: E501
        self._log_date_time = None
        self._channels = None
        self.discriminator = None
        if log_date_time is not None:
            self.log_date_time = log_date_time
        if channels is not None:
            self.channels = channels

    @property
    def log_date_time(self):
        """Gets the log_date_time of this EnergyFlowData.  # noqa: E501


        :return: The log_date_time of this EnergyFlowData.  # noqa: E501
        :rtype: str
        """
        return self._log_date_time

    @log_date_time.setter
    def log_date_time(self, log_date_time):
        """Sets the log_date_time of this EnergyFlowData.


        :param log_date_time: The log_date_time of this EnergyFlowData.  # noqa: E501
        :type: str
        """

        self._log_date_time = log_date_time

    @property
    def channels(self):
        """Gets the channels of this EnergyFlowData.  # noqa: E501


        :return: The channels of this EnergyFlowData.  # noqa: E501
        :rtype: list[EnergyFlowChannel]
        """
        return self._channels

    @channels.setter
    def channels(self, channels):
        """Sets the channels of this EnergyFlowData.


        :param channels: The channels of this EnergyFlowData.  # noqa: E501
        :type: list[EnergyFlowChannel]
        """

        self._channels = channels

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnergyFlowData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnergyFlowData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
