# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EnergyFlowStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_online': 'bool',
        'batt_mode': 'float'
    }

    attribute_map = {
        'is_online': 'isOnline',
        'batt_mode': 'battMode'
    }

    def __init__(self, is_online=None, batt_mode=None):  # noqa: E501
        """EnergyFlowStatus - a model defined in Swagger"""  # noqa: E501
        self._is_online = None
        self._batt_mode = None
        self.discriminator = None
        if is_online is not None:
            self.is_online = is_online
        if batt_mode is not None:
            self.batt_mode = batt_mode

    @property
    def is_online(self):
        """Gets the is_online of this EnergyFlowStatus.  # noqa: E501


        :return: The is_online of this EnergyFlowStatus.  # noqa: E501
        :rtype: bool
        """
        return self._is_online

    @is_online.setter
    def is_online(self, is_online):
        """Sets the is_online of this EnergyFlowStatus.


        :param is_online: The is_online of this EnergyFlowStatus.  # noqa: E501
        :type: bool
        """

        self._is_online = is_online

    @property
    def batt_mode(self):
        """Gets the batt_mode of this EnergyFlowStatus.  # noqa: E501


        :return: The batt_mode of this EnergyFlowStatus.  # noqa: E501
        :rtype: float
        """
        return self._batt_mode

    @batt_mode.setter
    def batt_mode(self, batt_mode):
        """Sets the batt_mode of this EnergyFlowStatus.


        :param batt_mode: The batt_mode of this EnergyFlowStatus.  # noqa: E501
        :type: float
        """

        self._batt_mode = batt_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnergyFlowStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnergyFlowStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
