# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class EnergyFlowChannel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel_name': 'str',
        'channel_type': 'str',
        'unit': 'str',
        'value': 'object'
    }

    attribute_map = {
        'channel_name': 'channelName',
        'channel_type': 'channelType',
        'unit': 'unit',
        'value': 'value'
    }

    def __init__(self, channel_name=None, channel_type=None, unit=None, value=None):  # noqa: E501
        """EnergyFlowChannel - a model defined in Swagger"""  # noqa: E501
        self._channel_name = None
        self._channel_type = None
        self._unit = None
        self._value = None
        self.discriminator = None
        if channel_name is not None:
            self.channel_name = channel_name
        if channel_type is not None:
            self.channel_type = channel_type
        if unit is not None:
            self.unit = unit
        if value is not None:
            self.value = value

    @property
    def channel_name(self):
        """Gets the channel_name of this EnergyFlowChannel.  # noqa: E501


        :return: The channel_name of this EnergyFlowChannel.  # noqa: E501
        :rtype: str
        """
        return self._channel_name

    @channel_name.setter
    def channel_name(self, channel_name):
        """Sets the channel_name of this EnergyFlowChannel.


        :param channel_name: The channel_name of this EnergyFlowChannel.  # noqa: E501
        :type: str
        """

        self._channel_name = channel_name

    @property
    def channel_type(self):
        """Gets the channel_type of this EnergyFlowChannel.  # noqa: E501


        :return: The channel_type of this EnergyFlowChannel.  # noqa: E501
        :rtype: str
        """
        return self._channel_type

    @channel_type.setter
    def channel_type(self, channel_type):
        """Sets the channel_type of this EnergyFlowChannel.


        :param channel_type: The channel_type of this EnergyFlowChannel.  # noqa: E501
        :type: str
        """

        self._channel_type = channel_type

    @property
    def unit(self):
        """Gets the unit of this EnergyFlowChannel.  # noqa: E501


        :return: The unit of this EnergyFlowChannel.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this EnergyFlowChannel.


        :param unit: The unit of this EnergyFlowChannel.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def value(self):
        """Gets the value of this EnergyFlowChannel.  # noqa: E501


        :return: The value of this EnergyFlowChannel.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this EnergyFlowChannel.


        :param value: The value of this EnergyFlowChannel.  # noqa: E501
        :type: object
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnergyFlowChannel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnergyFlowChannel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
