# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class HistoricalValues(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pv_system_id': 'str',
        'device_id': 'str',
        'data': 'list[HistoricalData]',
        'links': 'PagingLinks'
    }

    attribute_map = {
        'pv_system_id': 'pvSystemId',
        'device_id': 'deviceId',
        'data': 'data',
        'links': 'links'
    }

    def __init__(self, pv_system_id=None, device_id=None, data=None, links=None):  # noqa: E501
        """HistoricalValues - a model defined in Swagger"""  # noqa: E501
        self._pv_system_id = None
        self._device_id = None
        self._data = None
        self._links = None
        self.discriminator = None
        if pv_system_id is not None:
            self.pv_system_id = pv_system_id
        if device_id is not None:
            self.device_id = device_id
        if data is not None:
            self.data = data
        if links is not None:
            self.links = links

    @property
    def pv_system_id(self):
        """Gets the pv_system_id of this HistoricalValues.  # noqa: E501


        :return: The pv_system_id of this HistoricalValues.  # noqa: E501
        :rtype: str
        """
        return self._pv_system_id

    @pv_system_id.setter
    def pv_system_id(self, pv_system_id):
        """Sets the pv_system_id of this HistoricalValues.


        :param pv_system_id: The pv_system_id of this HistoricalValues.  # noqa: E501
        :type: str
        """

        self._pv_system_id = pv_system_id

    @property
    def device_id(self):
        """Gets the device_id of this HistoricalValues.  # noqa: E501


        :return: The device_id of this HistoricalValues.  # noqa: E501
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this HistoricalValues.


        :param device_id: The device_id of this HistoricalValues.  # noqa: E501
        :type: str
        """

        self._device_id = device_id

    @property
    def data(self):
        """Gets the data of this HistoricalValues.  # noqa: E501


        :return: The data of this HistoricalValues.  # noqa: E501
        :rtype: list[HistoricalData]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this HistoricalValues.


        :param data: The data of this HistoricalValues.  # noqa: E501
        :type: list[HistoricalData]
        """

        self._data = data

    @property
    def links(self):
        """Gets the links of this HistoricalValues.  # noqa: E501


        :return: The links of this HistoricalValues.  # noqa: E501
        :rtype: PagingLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this HistoricalValues.


        :param links: The links of this HistoricalValues.  # noqa: E501
        :type: PagingLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoricalValues, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoricalValues):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
