# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PagingLinks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'first': 'str',
        'prev': 'str',
        '_self': 'str',
        'next': 'str',
        'last': 'str',
        'total_items_count': 'int'
    }

    attribute_map = {
        'first': 'first',
        'prev': 'prev',
        '_self': 'self',
        'next': 'next',
        'last': 'last',
        'total_items_count': 'totalItemsCount'
    }

    def __init__(self, first=None, prev=None, _self=None, next=None, last=None, total_items_count=None):  # noqa: E501
        """PagingLinks - a model defined in Swagger"""  # noqa: E501
        self._first = None
        self._prev = None
        self.__self = None
        self._next = None
        self._last = None
        self._total_items_count = None
        self.discriminator = None
        if first is not None:
            self.first = first
        if prev is not None:
            self.prev = prev
        if _self is not None:
            self._self = _self
        if next is not None:
            self.next = next
        if last is not None:
            self.last = last
        if total_items_count is not None:
            self.total_items_count = total_items_count

    @property
    def first(self):
        """Gets the first of this PagingLinks.  # noqa: E501


        :return: The first of this PagingLinks.  # noqa: E501
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this PagingLinks.


        :param first: The first of this PagingLinks.  # noqa: E501
        :type: str
        """

        self._first = first

    @property
    def prev(self):
        """Gets the prev of this PagingLinks.  # noqa: E501


        :return: The prev of this PagingLinks.  # noqa: E501
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this PagingLinks.


        :param prev: The prev of this PagingLinks.  # noqa: E501
        :type: str
        """

        self._prev = prev

    @property
    def _self(self):
        """Gets the _self of this PagingLinks.  # noqa: E501


        :return: The _self of this PagingLinks.  # noqa: E501
        :rtype: str
        """
        return self.__self

    @_self.setter
    def _self(self, _self):
        """Sets the _self of this PagingLinks.


        :param _self: The _self of this PagingLinks.  # noqa: E501
        :type: str
        """

        self.__self = _self

    @property
    def next(self):
        """Gets the next of this PagingLinks.  # noqa: E501


        :return: The next of this PagingLinks.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this PagingLinks.


        :param next: The next of this PagingLinks.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def last(self):
        """Gets the last of this PagingLinks.  # noqa: E501


        :return: The last of this PagingLinks.  # noqa: E501
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this PagingLinks.


        :param last: The last of this PagingLinks.  # noqa: E501
        :type: str
        """

        self._last = last

    @property
    def total_items_count(self):
        """Gets the total_items_count of this PagingLinks.  # noqa: E501


        :return: The total_items_count of this PagingLinks.  # noqa: E501
        :rtype: int
        """
        return self._total_items_count

    @total_items_count.setter
    def total_items_count(self, total_items_count):
        """Sets the total_items_count of this PagingLinks.


        :param total_items_count: The total_items_count of this PagingLinks.  # noqa: E501
        :type: int
        """

        self._total_items_count = total_items_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PagingLinks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PagingLinks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
