# coding: utf-8

"""
    Solar.web Query API (SWQAPI)

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PvSystemList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pv_systems': 'list[PvSystem]',
        'links': 'PagingLinks'
    }

    attribute_map = {
        'pv_systems': 'pvSystems',
        'links': 'links'
    }

    def __init__(self, pv_systems=None, links=None):  # noqa: E501
        """PvSystemList - a model defined in Swagger"""  # noqa: E501
        self._pv_systems = None
        self._links = None
        self.discriminator = None
        if pv_systems is not None:
            self.pv_systems = pv_systems
        if links is not None:
            self.links = links

    @property
    def pv_systems(self):
        """Gets the pv_systems of this PvSystemList.  # noqa: E501


        :return: The pv_systems of this PvSystemList.  # noqa: E501
        :rtype: list[PvSystem]
        """
        return self._pv_systems

    @pv_systems.setter
    def pv_systems(self, pv_systems):
        """Sets the pv_systems of this PvSystemList.


        :param pv_systems: The pv_systems of this PvSystemList.  # noqa: E501
        :type: list[PvSystem]
        """

        self._pv_systems = pv_systems

    @property
    def links(self):
        """Gets the links of this PvSystemList.  # noqa: E501


        :return: The links of this PvSystemList.  # noqa: E501
        :rtype: PagingLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PvSystemList.


        :param links: The links of this PvSystemList.  # noqa: E501
        :type: PagingLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PvSystemList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PvSystemList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
